---
- name: Make sure the Podsync container is created and running
  tags:
    - setup-media
  docker_container:
    name: "podsync"
    image: "podsync:latest"
    pull: yes
    state: 'started'
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/podsync/data:/app/data"
    restart_policy: unless-stopped